"""Generate a transparency appendix (LaTeX) listing every prompt, the retrieved
verses, and BOTH responses. This is a resource for the paper -- full
reproducibility -- not written analysis.

Output -> paper/appendix_responses.tex   (\input by main.tex)

Run:  python scripts/make_appendix.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import config  # noqa: E402


def tex_escape(s: str) -> str:
    s = str(s)
    s = s.replace("\\", r"\textbackslash{}")
    for a, b in [("&", r"\&"), ("%", r"\%"), ("$", r"\$"), ("#", r"\#"),
                 ("_", r"\_"), ("{", r"\{"), ("}", r"\}"),
                 ("~", r"\textasciitilde{}"), ("^", r"\textasciicircum{}")]:
        s = s.replace(a, b)
    # Curly quotes / dashes -> safe ASCII-ish.
    for a, b in [("—", "---"), ("–", "--"), ("’", "'"),
                 ("‘", "'"), ("“", "``"), ("”", "''")]:
        s = s.replace(a, b)
    return s


def main() -> int:
    if not config.MODEL_OUTPUTS_CSV.exists():
        print("ERROR: run run_experiment.py first.", file=sys.stderr)
        return 1
    df = pd.read_csv(config.MODEL_OUTPUTS_CSV)
    df = df.sort_values("run").drop_duplicates(subset="id", keep="first")

    out = [
        "% Auto-generated by scripts/make_appendix.py -- do not hand-edit.",
        f"% Model: {tex_escape(df['model'].iloc[0])}; "
        f"retrieval: {tex_escape(df['retrieval_method'].iloc[0])}.",
        "",
    ]
    for r in df.itertuples(index=False):
        out.append(r"\subsection*{" + tex_escape(f"{r.id} ({r.category})") + "}")
        out.append(r"\noindent\textbf{Prompt:} " + tex_escape(r.prompt) + r"\\[2pt]")
        out.append(r"\textbf{Retrieved verses:} " + tex_escape(r.retrieved_refs) + r"\\[2pt]")
        out.append(r"\textbf{Baseline response:} " + tex_escape(r.baseline_response) + r"\\[4pt]")
        out.append(r"\textbf{Nishkama (RAG) response:} " + tex_escape(r.nishkama_response))
        out.append(r"\medskip")
        out.append("")

    (config.PAPER_DIR / "appendix_responses.tex").write_text("\n".join(out) + "\n")
    print(f"Wrote paper/appendix_responses.tex ({len(df)} prompts).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
